baseURL = 'https://thomas.sheards.net/'
locale = 'en-au'
title = "thomas' site"
#theme = ""

[[module.mounts]]
source = "content"
target = "content"

[[module.mounts]]

# place double pendulum series in both maths and computing
source = "content/hobbies/computing/double_pendulum"
target = "content/hobbies/maths/double_pendulum"

[markup]
  [markup.highlight]
    noClasses = true
    style = "onedark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
      [markup.goldmark.extensions.typographer]
        apostrophe = "'"
        leftDoubleQuote = '"'
        leftSingleQuote = "'"
        rightDoubleQuote = '"'
        rightSingleQuote = "'"

[params]
  math = true
  [params.meta]
  favicon = true
