baseURL = 'https://thomas.sheards.net/'
locale = 'en-au'
title = "thomas' site"
theme = ""

[markup]
  [markup.highlight]
    noClasses = true
    style = "onedark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
      [markup.goldmark.extensions.typographer]
        apostrophe = "'"
        leftDoubleQuote = '"'
        leftSingleQuote = "'"
        rightDoubleQuote = '"'
        rightSingleQuote = "'"

[params]
  math = true
  [params.meta]
  favicon = true
